spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bookkeepingdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false
mybatis:
  configuration:
    auto-mapping-behavior: full
    lazy-loading-enabled: true
  type-aliases-package: com.yy.bookkeeping.entity